- name: Follow Access and Error Logs
  sudo: yes
  command: le follow {{ item.path }} --name {{ item.name | quote }}
  when: logentries_account_key is defined
  with_items:
    - { path: "{{ staticsite_logs_path }}/access.log", name: "Staticsite Access" }
    - { path: "{{ staticsite_logs_path }}/error.log",  name: "Staticsite Error" }