postgresql:
  max_connections:      25
  shared_buffers:       256MB
  temp_buffers:         4MB
  work_mem:             4MB
  maintenance_work_mem: 64MB
  effective_cache_size: 512MB
memcached:
  size: 64

postgresql_railsapp_owner_password: test1234
postgresql_railsapp_app_password: abcd1234
railsapp_encryption_password: 1234s
