---
- name: Configure locale
  command: /usr/sbin/update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8
  sudo: yes

- name: Update apt cache
  apt:  update_cache=yes
  sudo: yes

# This is the main user for all deployment activities
- name: Create deployment user "deploy"
  user: name=deploy state=present shell=/bin/bash
  sudo: yes

# this is required for forwarding ssh keys when deploying
- name: Allow current user to connect to deploy user via ssh
  authorized_key: >
    user=deploy
    key="{{ lookup('file', github_public_key_location) }}"
  sudo: yes

# note: this disables sudo for the vagrant user on VMs
# use the deploy user from now on for bootstrapping
- name: Enable sudo for user "deploy"
  template: src=sudoers dest=/etc/sudoers validate="visudo -cf %s"
  sudo: yes


- name: Disable root SSH Access
  action: >
    lineinfile dest=/etc/ssh/sshd_config
    regexp="^PermitRootLogin"
    line="PermitRootLogin no" state=present
  sudo: yes
  remote_user: deploy
  register: disable_root_ssh_access

- name: Disable Password Authentication
  action: >
    lineinfile dest=/etc/ssh/sshd_config
    regexp="^PasswordAuthentication"
    line="PasswordAuthentication no" state=present
  sudo: yes
  remote_user: deploy
  register: disable_password_authentication

- name: restart SSH
  sudo: yes
  remote_user: deploy
  service: name=ssh state=restarted
  when: >
    disable_root_ssh_access|changed or
    disable_password_authentication|changed

- name: Add un-mirrored Ubuntu security repository
  sudo: yes
  remote_user: deploy
  lineinfile: >
    dest=/etc/apt/sources.list
    line='deb http://archive.ubuntu.com/ubuntu/ precise-security main restricted'

# Install the unattended-upgrades package which allows to easily
# install security updates. Note that this is not configured
# to automatically install these updates.

- name: Install security updater installer
  apt: pkg=unattended-upgrades state=latest
  remote_user: deploy
  sudo: yes

- name: Install security updates
  command: unattended-upgrades
  remote_user: deploy
  sudo: yes

- command: update-ca-certificates
  remote_user: deploy
  sudo: yes

- name: Install build environment
  apt: "pkg=build-essential,python-software-properties,python,g++,make,libreadline-dev,zlib1g-dev,libssl-dev,libxslt-dev,libxml2-dev,git,openssl,curl state=present"
  remote_user: deploy
  sudo: yes

- name: Install useful system monitoring tools
  apt: "pkg=vim,htop"
  remote_user: deploy
  sudo: yes

- name: Add Github to known hosts
  lineinfile: >
    dest=/etc/ssh/ssh_known_hosts
    line="github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
    owner=root
    group=root
    state=present
    insertafter=EOF
    mode=0644
    create=yes
  remote_user: deploy
  sudo: yes

- name: Create top-level directory structure for all projects/sites/apps/etc
  file: path=/u/ group=root owner=root mode=0755 state=directory
  sudo: yes
  remote_user: deploy