---
- hosts: all
  vars:
    http_port: 80
  remote_user: root
  tasks:
  - name: Configure locale
    command: /usr/sbin/update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8
    sudo: yes
  - name: Update apt cache
    apt:  update_cache=yes
    sudo: yes

  - name: Disable root SSH Access
    action: >
      lineinfile dest=/etc/ssh/sshd_config
      regexp="^PermitRootLogin"
      line="PermitRootLogin no" state=present
    sudo: yes
    register: disable_root_ssh_access
  - name: Disable Password Authentication
    action: >
      lineinfile dest=/etc/ssh/sshd_config
      regexp="^PasswordAuthentication"
      line="PasswordAuthentication no" state=present
    sudo: yes
    register: disable_password_authentication
  - name: restart SSH
    sudo: yes
    service: name=ssh state=restarted
    when: >
      disable_root_ssh_access|changed or
      disable_password_authentication|changed

  - name: Add un-mirrored Ubuntu security repository
    sudo: yes
    lineinfile: >
      dest=/etc/apt/sources.list
      line='deb http://archive.ubuntu.com/ubuntu/ precise-security main restricted'

  # Install the unattended-upgrades package which allows to easily
  # install security updates. Note that this is not configured
  # to automatically install these updates.

  - name: Install security updater installer
    apt: pkg=unattended-upgrades state=latest
    sudo: yes

  - name: Install security updates
    command: unattended-upgrades
    sudo: yes

  - command: update-ca-certificates
    sudo: yes

  - name: Install build environment
    apt: "pkg=build-essential,python-software-properties,python,g++,make,libreadline-dev,zlib1g-dev,libssl-dev,libxslt-dev,libxml2-dev,git,openssl,curl state=present"
    sudo: yes